### PR TITLE
Initial commit of OQS .Net C# wrapper.

### PR DESCRIPTION
**Pull request by christianpaquin**
Initial commit of OQS .Net C# wrapper.

### CODE REVIEW

**Comment by dstebila** [comment]
When I first tried to build on Windows 10 with VS 2017 Community Edition, I got the error:

    Assets file 'C:\Users\Douglas\Desktop\liboqs-csharp\dotnetOQSUnitTest\obj\project.assets.json' not
    found. Run a NuGet package restore to generate this file.

After Googling the error message, I found that

    MSBuild.exe dotnetOQS.sln /t:Restore

fixed the problem.  Is this a one-time problem because this was my first time using MSBuild ever, or is it something that should be part of the build instructions?

**Comment by dstebila** [comment]
Then I had to install .NET Core 1.1, which seems to no longer be the current version?

**Comment by dstebila** [comment]
Finally I get to the following error:

```
C:\Users\Douglas\Desktop\liboqs-csharp>dotnet dotnetOQSSample\bin\Release\netcoreapp1.1\dotnetOQSSample.dll
Starting KEM example
Enabled KEM mechanisms:

Unhandled Exception: System.TypeInitializationException: The type initializer for 'OpenQuantumSafe.KEM' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'OQS_KEM_alg_count' in DLL 'oqs.dll'.
   at OpenQuantumSafe.KEM.OQS_KEM_alg_count()
   at OpenQuantumSafe.KEM..cctor() in C:\Users\Douglas\Desktop\liboqs-csharp\dotnetOQS\KEM.cs:line 74
   --- End of inner exception stack trace ---
   at dotnetOQSSample.Program.example_kem() in C:\Users\Douglas\Desktop\liboqs-csharp\dotnetOQSSample\Program.cs:line 16
   at dotnetOQSSample.Program.Main(String[] args) in C:\Users\Douglas\Desktop\liboqs-csharp\dotnetOQSSample\Program.cs:line 128
```

**Comment by christianpaquin** [comment]
That feels like a setup issue. I think it’d be clear to a Visual Studio dev how to deal with that.

On Jan 31, 2019, at 5:03 PM, Douglas Stebila <notifications@github.com<mailto:notifications@github.com>> wrote:


When I first tried to build on Windows 10 with VS 2017 Community Edition, I got the error:

Assets file 'C:\Users\Douglas\Desktop\liboqs-csharp\dotnetOQSUnitTest\obj\project.assets.json' not
found. Run a NuGet package restore to generate this file.


After Googling the error message, I found that

MSBuild.exe dotnetOQS.sln /t:Restore


fixed the problem. Is this a one-time problem because this was my first time using MSBuild ever, or is it something that should be part of the build instructions?

**Comment by christianpaquin** [comment]
@dstebila, I'll try from a fresh VM tomorrow to see if I need to add additional installation instructions.

**Comment by christianpaquin** [comment]
Ok, I tried on a fresh VM; worked for me. A few things:

- Yes, the project targets .net core 1.1; not the current 2.0 or in-preview 3.0. Moving to a newer framework removes support to older platforms; although complicates install on new machines. I'll add a note in the readme. I suggest we leave this as is, and revisit prior to our v1.0 to see which platform is preferred (based on user feedback)
- Trying to build on the command line is error-prone (if a package is missing). That's what's described in the readme, for brevity reasons, but opening the solutions (both for OQS and the wrapper) in Visual Studio provides helpful messages to resolve issue (e.g., re-target the Windows SDK to build OQS, and a bunch of missing packages were retrieved automatically for the wrapper).
- I didn't get the error you last saw, wrt the missing QOS function. This is a fairly new function in OQS; did you download a fresh copy of the library from the master branch?
- Can we change the github project name? It might be better to call this liboqs-dotnet given the generalized platform that .net is
- Speaking of, .net also works on linux and macOS, so it would be interesting to try the project there too. I'm not sure how the DllImport would work on these platforms howerver... (I'll open an investigative issue for that)

**Comment by christianpaquin** [comment]
@dstebila; I've pushed more details on the build (and how to potentially resolve issues).

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
Got it to build successfully.  Yes, my mistake was using an old version of liboqs that didn't have the new function.  

I filled out the README a bit and have merged.

I also renamed the project to liboqs-dotnet.

**Pull request merged**
